version: "3.8"
services:
    redis:
      image: redis:alpine
      container_name: nuclearengine-redis
    webserver:
      image: nginx:alpine
      container_name: nuclearengine-webserver
      working_dir: /nuclearengine
      volumes:
          - ./public:/home/public
          - ./docker/nginx/conf.d:/etc/nginx/conf.d
      env_file:
        - config.env
      ports:
       - "80:80"
    php-fpm:
      build: docker/php-fpm
      container_name: nuclearengine-php-fpm
      working_dir: /nuclearengine
      volumes:
        - ./public:/home/public
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

